name: "Wärmepumpen Monitor"
description: "Trackt Verbrauch, JAZ, Energieleistung und Außentemperatur deiner Wärmepumpe"
version: "1.0.0"
slug: "waermepumpe_monitor"
init: false
arch:
  - aarch64
  - armv7
  - amd64
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "Web Interface"
map:
  - data:rw
